[mcp_servers.unity]
command = 'C:\Program Files\nodejs\node.exe'
args = ['C:\Users\zhn\AppData\Roaming\npm\node_modules\anklebreaker-unity-mcp\src\index.js']

[mcp_servers.unity.tools.unity_list_instances]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_select_instance]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_asset_list]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_search_assets]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_search_by_component]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_scene_hierarchy]
approval_mode = "approve"

[mcp_servers.unity.tools.unity_execute_code]
approval_mode = "approve"
